import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {storeData} from '@/lib/server/catalog';
import {Shop} from '@/components/shop';
import {Admin} from '@/components/admin';
export const dynamic='force-dynamic';
const routes:Record<string,string>={home:'Antojitos Cakes',catalogo:'Catálogo',producto:'Producto',ocasiones:'Por ocasión',carrito:'Mi carrito','finalizar-pedido':'Finalizar pedido',pedido:'Mi pedido',seguimiento:'Consulta tu pedido',sedes:'Nuestras sedes',contacto:'Contacto','preguntas-frecuentes':'Preguntas frecuentes',privacidad:'Política de privacidad',terminos:'Términos',admin:'Administración'};
export async function generateMetadata({params}:{params:Promise<{slug?:string[]}>}):Promise<Metadata>{const {slug=[]}=await params;const data=await storeData();const p=slug[0]==='producto'?data.products.find((p:any)=>p.slug===slug[1]):null;const title=p?.name||routes[slug[0]||'home']||data.pages.find((p:any)=>p.slug===slug[0])?.title||'Página no encontrada';const description=p?.short_description||'Descubre el catálogo de Antojitos Cakes, elige tus favoritos y crea tu pedido.';return {title:title==='Antojitos Cakes'?{absolute:title}:title,description,alternates:data.settings.site_url?{canonical:data.settings.site_url+'/'+slug.join('/')}:undefined,openGraph:{title,description,type:'website',locale:'es_VE'},robots:['admin','carrito','finalizar-pedido','pedido','seguimiento'].includes(slug[0])?{index:false,follow:false}:undefined};}
export default async function Page({params}:{params:Promise<{slug?:string[]}>}){const {slug=[]}=await params;const data=await storeData();if(slug[0]==='admin')return <Admin path={slug} store={data}/>;if(slug[0]!=='admin'&&slug.length>(['producto','pedido'].includes(slug[0])?2:1))notFound();if(slug[0]==='producto'&&!data.products.some((p:any)=>p.slug===slug[1]))notFound();if(!routes[slug[0]||'home']&&!data.pages.some((p:any)=>p.slug===slug[0]))notFound();const schema={'@context':'https://schema.org','@type':'Bakery',name:data.settings.name,telephone:data.settings.phone,email:data.settings.email,sameAs:[data.settings.instagram]};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><Shop path={slug} data={data}/></>}
