import {all,one,run,batch,sql,uid,now,settings,env,audit,HttpError,ensure,csrf,body,throttle,auth,passwordHash,equal,digest,random,cookie,cookieHeader,phone} from '@/lib/server/core';
import {seed,products,storeData,cartIdentity,getCart,mutateCart} from '@/lib/server/catalog';
import {createOrder,detail,slots,discount,updateStatus} from '@/lib/server/orders';
import {saveEntity,saveProduct,saveSettings,deactivate,report} from '@/lib/server/admin';
import {models,labels} from '@/lib/models';
export const dynamic='force-dynamic';
const response=(v:any,status=200,extra:Record<string,string>={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...extra}});
async function handler(r:Request){try{csrf(r);const url=new URL(r.url),path=url.pathname.replace(/^\/api\//,'').split('/'),[area,action,id]=path,m=r.method;if(area==='media'&&m==='GET')return response({error:'Las imágenes subidas no están habilitadas en esta edición gratuita.'},404);await seed();
if(area==='store'&&m==='GET')return response(await storeData());
if(area==='auth'&&action==='status'&&m==='GET'){let user=null;try{user=await auth(r)}catch{}return response({user,initialized:!!await one('SELECT id FROM users LIMIT 1')});}
if(area==='auth'&&action==='setup'&&m==='POST'){await throttle(r,'setup',5,900);const b=await body(r);ensure(env.ADMIN_SETUP_TOKEN&&typeof b.setup_token==='string'&&equal(b.setup_token,env.ADMIN_SETUP_TOKEN),'Código de activación incorrecto.',403);ensure(!await one('SELECT id FROM users LIMIT 1'),'La administración ya está activada.',409);ensure(typeof b.email==='string'&&b.email.length<=180&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email),'Correo inválido.');ensure(typeof b.password==='string'&&b.password.length>=14&&b.password.length<=128,'La contraseña debe tener entre 14 y 128 caracteres.');ensure(typeof b.name==='string'&&b.name.trim().length>=2&&b.name.length<=120,'Indica tu nombre.');await run('INSERT INTO users (id,name,email,password_hash,role,active) VALUES (?,?,?,?,\'ADMINISTRADOR\',1)','owner',b.name.trim(),b.email.trim().toLowerCase(),await passwordHash(b.password));await audit('owner','activar_administracion','users','owner');return response({ok:true});}
if(area==='auth'&&action==='login'&&m==='POST'){await throttle(r,'login',8,900);const b=await body(r);ensure(typeof b.email==='string'&&typeof b.password==='string'&&b.password.length<=128,'Credenciales inválidas.',401);const u=await one('SELECT * FROM users WHERE email=? AND active=1',b.email.trim().toLowerCase());const expected=u?.password_hash||'pbkdf2:100000:dummy:dummy';const hash=await passwordHash(b.password,expected.split(':')[2]);ensure(u&&equal(hash,expected),'Correo o contraseña incorrectos.',401);const token=random();await batch([sql('DELETE FROM sessions WHERE expires_at<?',Date.now()),sql('DELETE FROM rate_limits WHERE expires_at<?',Date.now()),sql('INSERT INTO sessions (id,user_id,expires_at) VALUES (?,?,?)',await digest(token),u.id,Date.now()+12*3600000)]);return response({ok:true},200,{'Set-Cookie':cookieHeader(r,'ac_session',token,12*3600)});}
if(area==='auth'&&action==='logout'&&m==='POST'){await run('DELETE FROM sessions WHERE id=?',await digest(cookie(r,'ac_session')));return response({ok:true},200,{'Set-Cookie':cookieHeader(r,'ac_session','',0)});}
if(area==='cart'){await throttle(r,'cart',120);const identity=await cartIdentity(r);const cart=m==='GET'?await getCart(identity.id):['POST','PATCH','DELETE'].includes(m)?await mutateCart(identity.id,m,await body(r)):null;ensure(cart,'Acción inválida.',405);return response(cart,200,identity.header?{'Set-Cookie':identity.header}:{});}
if(area==='slots'&&m==='GET'){await throttle(r,'slots',90);return response({slots:await slots(await settings(),url.searchParams.get('location')||'',url.searchParams.get('date')||'')});}
if(area==='benefit'&&m==='POST'){await throttle(r,'benefit',20);const b=await body(r),identity=await cartIdentity(r),cart=await getCart(identity.id);return response(await discount(String(b.code||'').slice(0,60),cart.subtotal_cents,b.delivery_type==='delivery'?cart.settings.delivery_fee_cents:0));}
if(area==='orders'&&!action&&m==='POST'){await throttle(r,'order',10,3600);const identity=await cartIdentity(r);return response(await createOrder(identity.id,await body(r)),201);}
if(area==='orders'&&action==='receipt'&&m==='GET'){await throttle(r,'receipt',60);ensure(/^[a-f0-9]{64}$/.test(id||''),'Enlace inválido.',404);return response(await detail(await one('SELECT * FROM orders WHERE token_hash=?',await digest(id))));}
if(area==='orders'&&action==='track'&&m==='POST'){await throttle(r,'track',12,900);const b=await body(r);ensure(typeof b.number==='string'&&/^AC-\d{6,12}$/i.test(b.number.trim())&&typeof b.phone==='string','Revisa el número de pedido y teléfono.');return response(await detail(await one('SELECT * FROM orders WHERE number=? AND phone=?',b.number.trim().toUpperCase(),phone(b.phone))));}
if(area==='events'&&m==='POST'){await throttle(r,'events',90);const b=await body(r);ensure(['session','view_product','search','add_to_cart','remove_from_cart','begin_checkout','whatsapp_click'].includes(b.event),'Evento inválido.');ensure(b.consent===true,'Medición no autorizada.',403);const identity=await cartIdentity(r);if(b.event==='session'&&await one("SELECT id FROM analytics_events WHERE event='session' AND session_id=? AND created_at>?",identity.id,new Date(Date.now()-30*60000).toISOString()))return response({ok:true});await run('INSERT INTO analytics_events (id,event,session_id,product_id,detail,created_at) VALUES (?,?,?,?,?,?)',uid(),b.event,identity.id,typeof b.product_id==='string'?b.product_id.slice(0,150):null,typeof b.detail==='string'?b.detail.slice(0,100):'',now());return response({ok:true});}
if(area==='admin'){const user=await auth(r);await throttle(r,'admin',200);if(action==='upload'&&m==='POST')return response({error:'La subida directa de imágenes está desactivada para mantener el proyecto 100% gratuito. Usa una URL o una imagen incluida en /public.'},501);
if(action==='settings'){if(m==='GET')return response(await settings());if(m==='PUT')return response(await saveSettings(await body(r),user.id));}
if(action==='account'&&m==='PUT'){const b=await body(r);ensure(typeof b.current_password==='string'&&b.current_password.length<=128&&typeof b.new_password==='string'&&b.new_password.length>=14&&b.new_password.length<=128,'Revisa las contraseñas. La nueva debe tener al menos 14 caracteres.');const u=await one('SELECT * FROM users WHERE id=?',user.id);ensure(equal(await passwordHash(b.current_password,u.password_hash.split(':')[2]),u.password_hash),'Contraseña actual incorrecta.',403);await batch([sql('UPDATE users SET password_hash=? WHERE id=?',await passwordHash(b.new_password),user.id),sql('DELETE FROM sessions WHERE user_id=?',user.id)]);await audit(user.id,'cambiar_contrasena','users',user.id);return response({ok:true},200,{'Set-Cookie':cookieHeader(r,'ac_session','',0)});}
if(action==='products'){if(m==='GET')return response(await products(true));if(['POST','PUT'].includes(m))return response(await saveProduct(id,await body(r),user.id));if(m==='DELETE')return response(await deactivate('products',id,user.id));}
if(action==='entities'){const entity=id,rowId=path[3];ensure(models[entity],'Sección inválida.',404);if(m==='GET')return response(await all(`SELECT * FROM ${entity} ORDER BY ${models[entity].fields.some(f=>f.key==='sort_order')?'sort_order,':''}rowid DESC`));if(['POST','PUT'].includes(m))return response(await saveEntity(entity,rowId,await body(r),user.id));if(m==='DELETE')return response(await deactivate(entity,rowId,user.id));}
if(action==='orders'){if(m==='GET'&&id)return response(await detail(await one('SELECT * FROM orders WHERE id=?',id),true));if(m==='PUT'&&id)return response(await updateStatus(id,await body(r),user.id));if(m==='GET'){const page=Math.max(1,Math.min(10000,Math.floor(Number(url.searchParams.get('page')||1))));ensure(Number.isFinite(page),'Página inválida.');const query=(url.searchParams.get('q')||'').slice(0,120),status=url.searchParams.get('status')||'';const where="WHERE (?='' OR number LIKE ? OR customer_name LIKE ? OR phone LIKE ?) AND (?='' OR status=?)",args=[query,'%'+query+'%','%'+query+'%','%'+query+'%',status,status];return response({items:await all(`SELECT id,number,customer_name,phone,total_cents,currency,currency_symbol,status,created_at,delivery_type,quote_count FROM orders ${where} ORDER BY id DESC LIMIT 50 OFFSET ?`,...args,(page-1)*50),total:(await one(`SELECT COUNT(*) n FROM orders ${where}`,...args)).n,page});}}
if(action==='customers'&&m==='GET'){if(id){const c=await one('SELECT * FROM customers WHERE id=?',id);ensure(c,'Cliente no encontrado.',404);return response({...c,orders:await all('SELECT id,number,total_cents,currency,currency_symbol,status,created_at FROM orders WHERE customer_id=? ORDER BY id DESC',id)});}return response(await all('SELECT c.*,COUNT(o.id) order_count,MAX(o.created_at) last_order FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id ORDER BY last_order DESC'));}
if(action==='audit'&&m==='GET')return response(await all('SELECT a.*,u.name actor FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT 300'));
if(action==='report'&&m==='GET'){const data=await report(url.searchParams.get('from')||now().slice(0,10),url.searchParams.get('to')||now().slice(0,10));if(url.searchParams.get('format')==='csv'){const cell=(v:any)=>{let x=String(v??'');if(/^[=+\-@\t\r]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"'};const rows=[['Pedido','Cliente','Teléfono','Importe registrado','Moneda','Estado','Entrega','Fecha','Artículos a cotizar'],...data.orders.map(o=>[o.number,o.customer_name,o.phone,(o.total_cents/100).toFixed(2),o.currency||'Por confirmar',labels[o.status],labels[o.delivery_type],o.created_at,o.quote_count])];return new Response('\uFEFF'+rows.map(row=>row.map(cell).join(';')).join('\r\n'),{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':`attachment; filename="pedidos-${data.from}-${data.to}.csv"`,'Cache-Control':'no-store'}});}return response(data);}}
throw new HttpError(404,'No encontramos esta ruta.');}catch(error){if(error instanceof HttpError)return response({error:error.message},error.status);console.error('Antojitos API:',error);if(String(error).includes('UNIQUE constraint'))return response({error:'Ese enlace o código ya existe. Revisa los datos.'},409);return response({error:'No pudimos completar la solicitud. Conservamos tus datos para que puedas volver a intentarlo.'},500);}}
export const GET=handler,POST=handler,PUT=handler,PATCH=handler,DELETE=handler;
