/** Integration acceptance tests against the compiled Worker in disposable local D1/R2. */
import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url),r=createRequire(require.resolve('wrangler/package.json'));const {Miniflare}=r('miniflare');
const files=(await readdir('dist/server',{recursive:true})).filter(x=>x.endsWith('.js')&&x!=='index.js');
const mf=new Miniflare({modules:['index.js',...files].map(x=>({type:'ESModule',path:'dist/server/'+x})),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{ADMIN_SETUP_TOKEN:'local-test-activation-code'},assets:{directory:'dist/client',binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},cf:false});
const successes=[];const pass=s=>{successes.push(s);console.log('PASS '+s)};
function client(){const cookies=new Map();return async(path,method='GET',data,expected=200,extra={})=>{const headers={host:'test.local','x-forwarded-host':'test.local',origin:'http://test.local',cookie:[...cookies].map(([k,v])=>k+'='+v).join(';'),...extra};if(data&&!(data instanceof FormData))headers['content-type']='application/json';let payload=data?JSON.stringify(data):undefined;if(data instanceof FormData){const req=new Request('http://test.local',{method:'POST',body:data});headers['content-type']=req.headers.get('content-type');payload=new Uint8Array(await req.arrayBuffer());}const res=await mf.dispatchFetch('http://test.local/api/'+path,{method,headers,...(payload?{body:payload}:{})});for(const c of res.headers.getSetCookie()){const [k,v]=c.split(';')[0].split('=');cookies.set(k,v)}const text=await res.text();let parsed;try{parsed=JSON.parse(text)}catch{parsed=text}assert.equal(res.status,expected,`${method} ${path}: ${text.slice(0,250)}`);return parsed}}
const admin=client(),buyer=client(),stranger=client();
try{
const db=await mf.getD1Database('DB');for(const name of (await readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort()){const migration=await readFile('drizzle/'+name,'utf8');for(const q of migration.split('--> statement-breakpoint'))if(q.trim())await db.prepare(q.trim()).run();}pass('Migración limpia de 28 tablas');
const store=await buyer('store');assert.equal(store.products.length,55);assert.equal(store.categories.length,5);assert.equal(store.products.filter(p=>p.price_cents===null).length,6);assert.equal(store.products.flatMap(p=>p.variants).length,39);pass('Importación real: 55 productos, 39 presentaciones, 6 por cotizar');
await stranger('admin/orders','GET',undefined,401);await stranger('auth/setup','POST',{setup_token:'bad'},403);await stranger('cart','POST',{quantity:1},403,{origin:'http://evil.invalid'});pass('Control de acceso y rechazo de origen externo');
const credentials={email:'qa@example.invalid',password:'Local-QA-only-password-726!'};await admin('auth/setup','POST',{...credentials,name:'Prueba local',setup_token:'local-test-activation-code'});await admin('auth/setup','POST',{...credentials,name:'Prueba local',setup_token:'local-test-activation-code'},409);await admin('auth/login','POST',{...credentials,password:'wrong'},401);await admin('auth/login','POST',credentials);assert.ok((await admin('auth/status')).user);pass('Activación única, contraseña y sesión de administración');
const p=store.products.find(p=>p.variants.length>1);await buyer('cart');await buyer('cart','POST',{product_id:p.id,variant_id:'invalid',option_ids:[],quantity:1,notes:''},400);let cart=await buyer('cart','POST',{product_id:p.id,variant_id:p.variants[0].id,option_ids:[],quantity:2,notes:'Prueba local'});assert.equal(cart.subtotal_cents,p.variants[0].price_cents*2);const item=cart.items[0];await stranger('cart');await stranger('cart','PATCH',{id:item.id,quantity:99},404);cart=await buyer('cart','PATCH',{id:item.id,quantity:3});assert.equal(cart.count,3);assert.equal((await buyer('cart')).count,3);cart=await buyer('cart','POST',{product_id:p.id,variant_id:p.variants[1].id,option_ids:[],quantity:2,notes:'Edición',item_id:item.id});assert.equal(cart.subtotal_cents,p.variants[1].price_cents*2);pass('Carrito persistente, variantes, cantidad, edición y aislamiento');
const category=await admin('admin/entities/categories','POST',{name:'QA local',slug:'qa-local',sort_order:20,active:true});const occasion=await admin('admin/entities/occasions','POST',{name:'QA ocasión',slug:'qa-ocasion',description:'Prueba',image:'',sort_order:0,active:true});const draft={name:'Producto QA',slug:'producto-qa',description:'Producto ficticio exclusivo de la prueba local',category_id:category.id,price_cents:1200,active:1,availability:'disponible',images:[],variants:[],options:[{group_name:'Sabor',name:'Vainilla',price_cents:200,required:1,active:1}],related_ids:[p.id],occasion_ids:[occasion.id]};const product=await admin('admin/products','POST',draft);let saved=(await admin('admin/products')).find(p=>p.id===product.id);await buyer('cart','POST',{product_id:product.id,option_ids:[],quantity:1,notes:''},400);cart=await buyer('cart','POST',{product_id:product.id,option_ids:[saved.options[0].id],quantity:1,notes:''});assert.equal(cart.items.at(-1).unit_cents,1400);pass('Categorías, ocasiones, producto y opción obligatoria');
const form={name:'PRUEBA LOCAL',surname:'QA',phone:'04120000000',email:'qa@example.invalid',delivery_type:'coordinar',accepted:true,idempotency_key:randomUUID(),cart_signature:cart.signature,total_cents:1};await buyer('orders','POST',{...form,accepted:false},400);await buyer('orders','POST',{...form,cart_signature:'0'.repeat(64)},409);await admin('admin/products/'+product.id,'PUT',{...saved,price_cents:1500});await buyer('orders','POST',form,409);cart=await buyer('cart');await buyer('events','POST',{event:'add_to_cart',consent:false},403);await buyer('events','POST',{event:'add_to_cart',consent:true,product_id:p.id});await buyer('orders','POST',{...form,cart_signature:cart.signature,expected_total_cents:1},409);const submitted={...form,cart_signature:cart.signature,expected_total_cents:cart.subtotal_cents};const created=await buyer('orders','POST',submitted,201),repeated=await buyer('orders','POST',submitted,201);assert.deepEqual(created,repeated);assert.equal((await buyer('cart')).count,0);const receipt=await buyer('orders/receipt/'+created.receipt);assert.equal(receipt.total_cents,cart.subtotal_cents);assert.equal(receipt.number,'AC-000001');assert.ok(receipt.whatsapp_url.startsWith('https://wa.me/584249012343?text='));assert.ok(!('internal_notes'in receipt)&&!('token_hash'in receipt));await stranger('orders/track','POST',{number:created.number,phone:'04120000001'},404);assert.equal((await buyer('orders/track','POST',{number:created.number,phone:form.phone})).id,receipt.id);pass('Pedido transaccional, recálculo, precio desactualizado, idempotencia y seguimiento privado');
await admin('admin/products/'+product.id,'DELETE');await admin('admin/products/'+p.id,'PUT',{...p,name:p.name+' EDITADO',price_cents:9999});const preserved=await buyer('orders/receipt/'+created.receipt);assert.deepEqual(preserved.items,receipt.items);assert.equal(preserved.total_cents,receipt.total_cents);pass('Historial conserva nombres, opciones y precios tras edición y eliminación');
await admin('admin/orders/'+receipt.id,'PUT',{status:'ENTREGADO',internal_notes:''},400);for(const status of ['CONFIRMADO','EN_PREPARACION','LISTO','ENTREGADO'])await admin('admin/orders/'+receipt.id,'PUT',{status,internal_notes:'Nota solo interna'});const tracked=await buyer('orders/track','POST',{number:created.number,phone:form.phone});assert.equal(tracked.history.length,5);assert.equal(tracked.status,'ENTREGADO');assert.ok(!JSON.stringify(tracked).includes('Nota solo interna'));pass('Transiciones de estado, historial y privacidad de notas internas');
const quote=store.products.find(p=>p.price_cents===null);cart=await buyer('cart','POST',{product_id:quote.id,option_ids:[],quantity:1,notes:''});assert.equal(cart.quote_count,1);const createdQuote=await buyer('orders','POST',{...form,idempotency_key:randomUUID(),cart_signature:cart.signature},201);assert.equal((await buyer('orders/receipt/'+createdQuote.receipt)).quote_count,1);pass('Pedidos por cotizar sin inventar precios');
const loc=store.locations[0],date='2030-06-03';await admin('admin/entities/business_hours','POST',{location_id:loc.id,weekday:'1',opens:'08:00',closes:'10:00',active:true});let config=await admin('admin/settings');await admin('admin/settings','PUT',{...config,blocked_dates:[''],pickup_enabled:true,delivery_enabled:true,delivery_fee_cents:500,schedule_enabled:true,schedule_location_id:loc.id,lead_hours:24});assert.deepEqual((await buyer('slots?location='+loc.id+'&date='+date)).slots,['08:00','08:30','09:00','09:30']);await admin('admin/settings','PUT',{...config,blocked_dates:[date]});assert.deepEqual((await buyer('slots?location='+loc.id+'&date='+date)).slots,[]);await admin('admin/settings','PUT',config);pass('Configuración, días, horarios, anticipación y fechas bloqueadas');
const pay=await admin('admin/entities/payment_methods','POST',{name:'Pago QA local',instructions:'Solo prueba',active:true,sort_order:0});await admin('admin/entities/web_benefits','POST',{title:'QA descuento',code:'QA10',type:'porcentaje',value:10,minimum_cents:0,description:'Prueba local',active:true});cart=await buyer('cart','POST',{product_id:'racion-brownie',option_ids:[],quantity:2,notes:''});const benefit=await buyer('benefit','POST',{code:'QA10',delivery_type:'coordinar'});assert.equal(benefit.discount,Math.round(cart.subtotal_cents*.1));await buyer('orders','POST',{...form,idempotency_key:randomUUID(),cart_signature:cart.signature},400);const discounted=await buyer('orders','POST',{...form,idempotency_key:randomUUID(),cart_signature:cart.signature,payment_method:pay.id,benefit_code:'QA10'},201);assert.equal((await buyer('orders/receipt/'+discounted.receipt)).total_cents,cart.subtotal_cents-benefit.discount);pass('Métodos de pago configurables y descuento calculado en servidor');
for(const [entity,body] of [['banners',{title:'QA banner',text:'Prueba',image:'',cta:'Ver',url:'/catalogo',active:true}],['campaigns',{title:'QA campaña',text:'Prueba',image:'',cta:'Ver',url:'/catalogo',starts_at:'2020-01-01T00:00',ends_at:'2040-01-01T00:00',active:true}],['faqs',{question:'¿Prueba?',answer:'Respuesta local.',active:true}],['pages',{title:'Página QA',slug:'pagina-qa',body:'Documento de prueba exclusivamente local.',active:true}]]){const e=await admin('admin/entities/'+entity,'POST',body);assert.ok((await buyer('store'))[entity].some(x=>x.id===e.id));await admin('admin/entities/'+entity+'/'+e.id,'DELETE');assert.ok(!(await buyer('store'))[entity].some(x=>x.id===e.id));}pass('Banners, campañas, preguntas y páginas: publicación y desactivación');
const upload=new FormData();upload.set('file',new File([await readFile('public/brand/logo.jpg')],'qa.jpg',{type:'image/jpeg'}));const media=await admin('admin/upload','POST',upload);const fetched=await mf.dispatchFetch('http://test.local'+media.src);assert.equal(fetched.status,200);assert.equal((await fetched.arrayBuffer()).byteLength,(await readFile('public/brand/logo.jpg')).byteLength);const invalid=new FormData();invalid.set('file',new File(['<svg>bad</svg>'],'bad.png',{type:'image/png'}));await admin('admin/upload','POST',invalid,400);pass('Subida R2, recuperación de imagen y validación del formato');
const today=new Date().toISOString().slice(0,10);const report=await admin('admin/report?from='+today+'&to='+today);assert.equal(report.summary.count,3);assert.ok(report.top.length);assert.equal(report.customers[0].count,3);assert.equal(report.conversion,100);assert.match(await admin('admin/report?from='+today+'&to='+today+'&format=csv'),/AC-000001/);assert.equal((await admin('admin/customers')).length,1);assert.equal((await admin('admin/customers/'+(await admin('admin/customers'))[0].id)).orders.length,3);assert.ok((await admin('admin/audit')).length>15);pass('Reportes reales, conversión, clientes, exportación CSV y auditoría');
await admin('admin/account','PUT',{current_password:credentials.password,new_password:'Another-local-test-only-password'});await admin('admin/orders','GET',undefined,401);await admin('auth/login','POST',credentials,401);await admin('auth/login','POST',{...credentials,password:'Another-local-test-only-password'});await admin('auth/logout','POST',{});await admin('admin/orders','GET',undefined,401);pass('Cambio de contraseña invalida sesiones; cierre de sesión efectivo');
console.log('\n'+successes.length+' grupos de pruebas completados. Solo datos ficticios en base desechable.');
}finally{await mf.dispose()}
