'use client';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
export function Choice({value,onChange,options,label,disabled=false}:any){return <Select value={String(value||'_empty')} onValueChange={v=>onChange(v==='_empty'?'':v)} disabled={disabled}><SelectTrigger className="field-select" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map((o:any)=><SelectItem key={o.value||'_empty'} value={String(o.value||'_empty')}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Check({checked,onChange,children}:any){return <label className="check-label"><Checkbox checked={!!checked} onCheckedChange={v=>onChange(v===true)}/>{children}</label>}
export function Toggle({checked,onChange,children}:any){return <label className="check-label"><Switch checked={!!checked} onCheckedChange={onChange}/>{children}</label>}
export function ImageInput({value,onChange,label='Imagen'}:any){return <div className="stack small-gap"><span className="field-label">{label}</span>{value&&<img className="image-preview" src={value} alt="Vista previa"/>}<label>URL o ruta de imagen<input value={value||''} onChange={e=>onChange(e.target.value)} placeholder="https://... o /products/archivo.webp"/></label><small className="muted">Esta edición gratuita usa las imágenes incluidas en la web o una URL pública. No requiere R2 ni método de pago.</small>{value&&<button className="text-link" type="button" onClick={()=>onChange('')}>Quitar imagen</button>}</div>}
export function DataTable({columns,rows}:any){return <div className="table-wrap"><Table><TableHeader><TableRow>{columns.map((c:string)=><TableHead key={c}>{c}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row:any[],i:number)=><TableRow key={i}>{row.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={columns.length}><p className="table-empty">Aún no hay registros para mostrar.</p></TableCell></TableRow>}</TableBody></Table></div>}
export function Confirm({open,onClose,onConfirm}:any){return <AlertDialog open={open} onOpenChange={v=>!v&&onClose()}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Retirar de la tienda?</AlertDialogTitle><AlertDialogDescription>El registro dejará de mostrarse. Los pedidos anteriores conservarán su información.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={onConfirm}>Retirar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
