export type Field={key:string,label:string,type?:string,required?:boolean,ref?:string,options?:string[]};
export const models:Record<string,{label:string,fields:Field[]}>= {
categories:{label:'Categorías',fields:[{key:'name',label:'Nombre',required:true},{key:'slug',label:'Enlace'},{key:'parent_id',label:'Categoría principal',ref:'categories'},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Visible',type:'boolean'}]},
occasions:{label:'Ocasiones',fields:[{key:'name',label:'Nombre',required:true},{key:'slug',label:'Enlace'},{key:'description',label:'Descripción',type:'textarea'},{key:'image',label:'Imagen',type:'image'},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Visible',type:'boolean'}]},
campaigns:{label:'Campañas',fields:[{key:'title',label:'Título',required:true},{key:'text',label:'Texto',type:'textarea'},{key:'image',label:'Imagen',type:'image'},{key:'cta',label:'Texto del botón'},{key:'url',label:'Destino del botón'},{key:'product_id',label:'Producto relacionado',ref:'products'},{key:'starts_at',label:'Inicio',type:'datetime-local'},{key:'ends_at',label:'Fin',type:'datetime-local'},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Activa',type:'boolean'}]},
banners:{label:'Banners',fields:[{key:'title',label:'Título',required:true},{key:'text',label:'Texto',type:'textarea'},{key:'image',label:'Imagen',type:'image'},{key:'cta',label:'Texto del botón'},{key:'url',label:'Destino del botón'},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Visible',type:'boolean'}]},
locations:{label:'Sedes',fields:[{key:'name',label:'Nombre',required:true},{key:'address',label:'Dirección',type:'textarea'},{key:'maps_url',label:'Enlace al mapa'},{key:'phone',label:'Teléfono'},{key:'whatsapp',label:'WhatsApp con código de país'},{key:'hours_text',label:'Horario visible'},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Visible',type:'boolean'}]},
business_hours:{label:'Horarios',fields:[{key:'location_id',label:'Sede',ref:'locations',required:true},{key:'weekday',label:'Día',options:['0','1','2','3','4','5','6']},{key:'opens',label:'Apertura',type:'time',required:true},{key:'closes',label:'Cierre',type:'time',required:true},{key:'active',label:'Disponible',type:'boolean'}]},
payment_methods:{label:'Métodos de pago',fields:[{key:'name',label:'Nombre',required:true},{key:'instructions',label:'Instrucciones',type:'textarea'},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Activo',type:'boolean'}]},
web_benefits:{label:'Beneficios web',fields:[{key:'title',label:'Nombre',required:true},{key:'code',label:'Código',required:true},{key:'type',label:'Tipo',options:['porcentaje','importe','envio','producto','personalizado']},{key:'value',label:'Valor (% o centavos)',type:'number'},{key:'minimum_cents',label:'Importe mínimo en centavos',type:'number'},{key:'description',label:'Condiciones / beneficio adicional',type:'textarea'},{key:'starts_at',label:'Inicio',type:'datetime-local'},{key:'ends_at',label:'Fin',type:'datetime-local'},{key:'active',label:'Activo',type:'boolean'}]},
faqs:{label:'Preguntas frecuentes',fields:[{key:'question',label:'Pregunta',required:true},{key:'answer',label:'Respuesta',type:'textarea',required:true},{key:'sort_order',label:'Orden',type:'number'},{key:'active',label:'Visible',type:'boolean'}]},
pages:{label:'Políticas y páginas',fields:[{key:'title',label:'Título',required:true},{key:'slug',label:'Enlace',required:true},{key:'body',label:'Contenido',type:'textarea'},{key:'active',label:'Publicada',type:'boolean'}]}
};
export const states=['NUEVO','CONFIRMADO','EN_PREPARACION','LISTO','ENTREGADO','CANCELADO'];
export const labels:Record<string,string>={NUEVO:'Nuevo',CONFIRMADO:'Confirmado',EN_PREPARACION:'En preparación',LISTO:'Listo',ENTREGADO:'Entregado',CANCELADO:'Cancelado',por_confirmar:'Por confirmar',disponible:'Disponible',agotado:'Agotado',retiro:'Retiro en tienda',delivery:'Entrega a domicilio',coordinar:'Por coordinar',porcentaje:'Porcentaje',importe:'Importe',envio:'Envío',producto:'Producto adicional',personalizado:'Personalizado'};
export const money=(n:number,s:any={})=>`${s.currency_symbol||'$'}${(Number(n||0)/100).toLocaleString('es-VE',{minimumFractionDigits:2,maximumFractionDigits:2})}${s.currency?' '+s.currency:''}`;
export const slugify=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const dateLabel=(s:string)=>new Date(s).toLocaleString('es-VE',{timeZone:'America/Caracas',dateStyle:'medium',timeStyle:'short'});
export const defaults={name:'Antojitos Cakes',tagline:'Creadora de la Flor de Otoño y Antojibrownie',rif:'J-29751427-9',logo:'/brand/logo.jpg',email:'Antojitoscakes@hotmail.com',phone:'0286-9221624',instagram:'https://www.instagram.com/antojitoscakespzo/',whatsapp:'584249012343',hours_text:'8:00 a. m. a 5:30 p. m.',currency:'',currency_symbol:'$',pickup_enabled:false,delivery_enabled:false,delivery_fee_cents:0,schedule_enabled:false,schedule_location_id:'',lead_hours:0,slot_minutes:30,blocked_dates:[] as string[],hero_title:'Siempre hay un motivo para un antojo.',hero_text:'Flor de Otoño, Antojibrownie y ese sabor que hace especial tu día. Elige el tuyo y crea tu pedido.',hero_image:'/products/chocofresa.webp',hero_product:'torta-chocofresa-arequipefresa',show_email:true,show_surname:true,ga4_id:'',meta_pixel_id:'',site_url:''};
